In [1]:
# Tensors are multi-dimensional arrays
# 0D arrays = 0D tensors similarly all...
# 1D tensors is combination of 0D tensors
# 2D is of 1D AND 3D is of 2D...
# To determine shape, just move in reverse way...
# No of 2D tensors in 3D tensor...1D in a 2D tensor and 0D in 1d Tensors

In [2]:
import tensorflow as tf


In [3]:
tensor_zero_dim = tf.constant(4)
print(tensor_zero_dim)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_dim = tf.constant([2,0,-3])
print(tensor_one_dim)
# if one given is float...it will consider all as float

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [5]:
tensor_two_dim = tf.constant([[1,2,3],
                              [4,5,6],
                              [7,8,9]
                        ])
print(tensor_two_dim)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [6]:
tensor_three_dim = tf.constant([[ [1,2,3], [4,5,6],  [7,8,9] ],
                              [[11,12,13], [14,15,16],  [17,18,19]]])
print(tensor_three_dim)
# For 4D tensor...uhh need many 3D tensors...

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]], shape=(2, 3, 3), dtype=int32)


In [7]:
# SHAPES OF TENSORS
print(tensor_zero_dim.shape)
print(tensor_one_dim.shape)
print(tensor_two_dim.shape)
print(tensor_three_dim.shape)

()
(3,)
(3, 3)
(2, 3, 3)


In [8]:
# DATATYPES
tensor_one_dim = tf.constant([2,0,-3] , dtype=tf.float32)
print(tensor_one_dim)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)


In [9]:
# CASTING
tensor_one_dim = tf.constant([2,0,-3] , dtype=tf.float32)
casted_tensor_one_dim = tf.cast(tensor_one_dim,dtype=tf.int64)
print(tensor_one_dim)
print(casted_tensor_one_dim)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 -3], shape=(3,), dtype=int64)


In [10]:
casted_tensor_one_dim = tf.cast(tensor_one_dim,dtype=tf.bool)
print(tensor_one_dim)
print(casted_tensor_one_dim)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [11]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [12]:
tensor_string = tf.constant(["Hello","World"])
print(tensor_string)

tf.Tensor([b'Hello' b'World'], shape=(2,), dtype=string)


In [13]:
import numpy as np
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [14]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [15]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns = None,
    batch_shape = None,
    dtype = tf.float32,
    name = None
)
print(eye_tensor)
# no of cols automatically  became 3...
# we can keep different no of rows n cols also...

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [16]:
print(3*eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [17]:
eye_tensor_1 = tf.eye(
    num_rows = 3,
    num_columns = 5,
    batch_shape = None,
    dtype = tf.float32,
    name = None
)
print(eye_tensor_1)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]], shape=(3, 5), dtype=float32)


In [18]:
eye_tensor_2 = tf.eye(
    num_rows = 3,
    num_columns = None,
    batch_shape = [2,],
    dtype = tf.float32,
    name = None
)
print(eye_tensor_2)
# batch shapes basically used for more than 2D...if we give 2,4...
# then shape = (2,4,3,3)...4D matrix

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [19]:
fill_tensor = tf.fill(
    [3,4],5,name=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [20]:
ones_tensor = tf.ones(
    [2,3,5],tf.float32,name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(2, 3, 5), dtype=float32)


In [21]:
# ones_like => tensor with 1s with same shape as original tensor
ones_like_tensor = tf.ones_like(
    fill_tensor,tf.float64
)
print(ones_like_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float64)


In [22]:
zeros_tensor = tf.zeros(
    [2,3,5],tf.float32,name=None
)
print(zeros_tensor)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(2, 3, 5), dtype=float32)


In [23]:
rank_tensor = tf.constant([[1,2,3],[4,5,6]])
print(tf.rank(rank_tensor))

tf.Tensor(2, shape=(), dtype=int32)


In [24]:
size_tensor = tf.constant([[1,2,3],[4,5,6]])
print(tf.size(size_tensor))

tf.Tensor(6, shape=(), dtype=int32)


In [25]:
shape_tensor = tf.constant([[1,2,3],[4,5,6]])
print(tf.shape(shape_tensor))

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [26]:
# Creating tensors which takes random values
random_tensor = tf.random.normal(
    shape=[3,4],
    mean= 0.0,
    stddev = 1.0,
    dtype = tf.float32,
    seed = None,
    name = None
)
print(random_tensor)
# all elements will be near mean
# with increase in SD range of elements increases...
# like mean = 100 and sd = 10
# then maybe 95 to 105 can be elements from...
# if mean = 100 sd = 2.5
# then it maybe from 98 to 102...

tf.Tensor(
[[ 0.92184144  1.2762344   0.06759333 -1.384439  ]
 [ 1.814457   -0.25994575  0.92927     0.70452774]
 [ 1.3749666   0.18290964 -0.456279    0.5034326 ]], shape=(3, 4), dtype=float32)


In [27]:
uniform_tensor = tf.random.uniform(
    shape=[3,4],
    minval= 0,
    maxval = 0.5,
    dtype = tf.float32,
    seed = None,
    name = None
)
print(uniform_tensor)
# default maxval is 1
# In uniform dist...all values between them have equal prob to get picked...
# In normal dist... all values dont have equal prob...values near mean have more prob...

tf.Tensor(
[[0.19412601 0.24288988 0.1263082  0.39266104]
 [0.43697888 0.15684909 0.26101995 0.37913102]
 [0.4588954  0.42804676 0.34699064 0.18920428]], shape=(3, 4), dtype=float32)


In [28]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [29]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
# same values as upper

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [30]:
tf.random.set_seed(10)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
# different

tf.Tensor([3 4 2], shape=(3,), dtype=int32)
tf.Tensor([3 3 3], shape=(3,), dtype=int32)
tf.Tensor([0 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [31]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=1))
# only last one changed

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([4 1 3], shape=(3,), dtype=int32)


In [32]:
# TENSOR INDEXING
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)


In [33]:
print(tensor_indexed[:4])

tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)


In [34]:
print(tf.range(2,6))

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [35]:
tensor_two_dim = tf.constant([[1,2,3],
                              [4,5,6],
                              [7,8,9]
                        ])
print(tensor_two_dim[:,:1])

tf.Tensor(
[[1]
 [4]
 [7]], shape=(3, 1), dtype=int32)


In [36]:
tensor_three_dim = tf.constant([[ [1,2,3], [4,5,6],  [7,8,9] ],
                              [[11,12,13], [14,15,16],  [17,18,19]]])
print(tensor_three_dim[1,1:3,:])
# ... also used for all selection

tf.Tensor(
[[14 15 16]
 [17 18 19]], shape=(2, 3), dtype=int32)


In [37]:
# Tensorflow Maths
# abs => gives absolute value  => -ve to +ve
x_abs = tf.constant([-2.25,3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [38]:
x_abs_com = tf.constant([-2.25 + 3.25j])
tf.abs(x_abs_com)
# complex no abs value => (a^2 + b^2)^(1/2)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([3.95284708])>

In [39]:
tf.sqrt(((-2.25)**2) + (3.25**2))

<tf.Tensor: shape=(), dtype=float32, numpy=3.952847>

In [40]:
x_1 = tf.constant([1,2,3,4,5],tf.int64)
x_2 = tf.constant([6,7,8,9,10],tf.int64)
print(tf.add(x_1,x_2))
print(tf.multiply(x_1,x_2))
print(tf.subtract(x_1,x_2))
print(tf.divide(x_1,x_2))

tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int64)
tf.Tensor([ 6 14 24 36 50], shape=(5,), dtype=int64)
tf.Tensor([-5 -5 -5 -5 -5], shape=(5,), dtype=int64)
tf.Tensor([0.16666667 0.28571429 0.375      0.44444444 0.5       ], shape=(5,), dtype=float64)


In [41]:
# if there's no num in division...we can use...tf.math.divide_no_nan
# cant be tf.int64/32
x_1 = tf.constant([1,2,3,4,5],tf.float64)
x_2 = tf.constant([6,7,np.NaN,9,10],tf.float64)
print(tf.math.divide_no_nan(x_1,x_2))

tf.Tensor([0.16666667 0.28571429        nan 0.44444444 0.5       ], shape=(5,), dtype=float64)


In [42]:
# If size of 1 tensor is 1...then it is broadcasted...
x_1 = tf.constant([1,2,3,4,5],tf.int64)
x_2 = tf.constant([6],tf.int64)
print(tf.add(x_1,x_2))
print(tf.multiply(x_1,x_2))
print(tf.subtract(x_1,x_2))
print(tf.divide(x_1,x_2))

tf.Tensor([ 7  8  9 10 11], shape=(5,), dtype=int64)
tf.Tensor([ 6 12 18 24 30], shape=(5,), dtype=int64)
tf.Tensor([-5 -4 -3 -2 -1], shape=(5,), dtype=int64)
tf.Tensor([0.16666667 0.33333333 0.5        0.66666667 0.83333333], shape=(5,), dtype=float64)


In [43]:
x_1 = tf.constant([1,2,3,4,5],tf.int64)
x_2 = tf.constant([[6],[7]],tf.int64)
print(tf.add(x_1,x_2))
# 1 2 3 4 5      6 6 6 6 6
#            *
# 1 2 3 4 5      7 7 7 7 7
# It happened like this...

tf.Tensor(
[[ 7  8  9 10 11]
 [ 8  9 10 11 12]], shape=(2, 5), dtype=int64)


In [44]:
x_1 = tf.constant([1,2,34,4,5],tf.int64)
x_2 = tf.constant([6,7,-9,9,3],tf.int64)
print(tf.math.maximum(x_1,x_2))
print(tf.math.minimum(x_1,x_2))
# compares between same indexes and reverses position

tf.Tensor([ 6  7 34  9  5], shape=(5,), dtype=int64)
tf.Tensor([ 1  2 -9  4  3], shape=(5,), dtype=int64)


In [45]:
x_1 = tf.constant([1,2,34,4,5],tf.int64)
x_2 = tf.constant([6],tf.int64)
print(tf.math.maximum(x_1,x_2))
print(tf.math.minimum(x_1,x_2))
# yeah broadcastinggg

tf.Tensor([ 6  6 34  6  6], shape=(5,), dtype=int64)
tf.Tensor([1 2 6 4 5], shape=(5,), dtype=int64)


In [46]:
x_arg = tf.constant([[1,3,2],[4,5,6],[7,8,9]])
print(tf.math.argmax(x_arg),0)
print(tf.math.argmin(x_arg),0)
# 1 3 2
# 4 5 6
# 7 8 9
# compared cols wise...axis is 0
# axis = 1...row wise

tf.Tensor([2 2 2], shape=(3,), dtype=int64) 0
tf.Tensor([0 0 0], shape=(3,), dtype=int64) 0


In [47]:
x_arg = tf.constant([[1,3,2],[4,5,6],[7,8,9]])
print(tf.math.argmax(x_arg, axis = 1))
print(tf.math.argmin(x_arg, axis = 1))

tf.Tensor([1 2 2], shape=(3,), dtype=int64)
tf.Tensor([0 0 0], shape=(3,), dtype=int64)


In [48]:
x_1 = tf.constant([1,2,34,4,5],tf.int64)
x_2 = tf.constant([1],tf.int64)
print(tf.math.equal(x_1,x_2))


tf.Tensor([ True False False False False], shape=(5,), dtype=bool)


In [49]:
print(tf.pow(x_1,x_2))
# val to power val of same index in other one

tf.Tensor([ 1  2 34  4  5], shape=(5,), dtype=int64)


In [50]:
tensor_two_dim = tf.constant([[1,2,3],
                              [4,5,6],
                              [7,8,9]
                        ],dtype = tf.float64)
print(tensor_two_dim)
print(tf.math.reduce_sum(tensor_two_dim, axis=None, keepdims=None))
print(tf.math.reduce_max(tensor_two_dim, axis=None, keepdims=None))
print(tf.math.reduce_min(tensor_two_dim, axis=None, keepdims=None))

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float64)
tf.Tensor(45.0, shape=(), dtype=float64)
tf.Tensor(9.0, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)


In [51]:
print(tf.math.reduce_sum(tensor_two_dim, axis=0, keepdims=None))
print(tf.math.reduce_sum(tensor_two_dim, axis=1, keepdims=None))
print(tf.math.reduce_max(tensor_two_dim, axis=0, keepdims=None))
print(tf.math.reduce_max(tensor_two_dim, axis=1, keepdims=None))
print(tf.math.reduce_mean(tensor_two_dim, axis=0, keepdims=None))
print(tf.math.reduce_mean(tensor_two_dim, axis=1, keepdims=None))
print(tf.math.reduce_std(tensor_two_dim, axis=0, keepdims=False))
print(tf.math.reduce_std(tensor_two_dim, axis=1, keepdims=None))
# If keepdims = True...shape will be same as of input tensor...

tf.Tensor([12. 15. 18.], shape=(3,), dtype=float64)
tf.Tensor([ 6. 15. 24.], shape=(3,), dtype=float64)
tf.Tensor([7. 8. 9.], shape=(3,), dtype=float64)
tf.Tensor([3. 6. 9.], shape=(3,), dtype=float64)
tf.Tensor([4. 5. 6.], shape=(3,), dtype=float64)
tf.Tensor([2. 5. 8.], shape=(3,), dtype=float64)
tf.Tensor([2.44948974 2.44948974 2.44948974], shape=(3,), dtype=float64)
tf.Tensor([0.81649658 0.81649658 0.81649658], shape=(3,), dtype=float64)


In [52]:
x_1 = tf.constant([1,2,34,4,5],tf.float64)
print(tf.math.sigmoid(x_1))
# LOGISTIC REGRESSION MAI USE...

tf.Tensor([0.73105858 0.88079708 1.         0.98201379 0.99330715], shape=(5,), dtype=float64)


In [53]:
tf.math.top_k(tensor_two_dim, k=1)
# top values / max values first
# their indices second...

TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=float64, numpy=
array([[3.],
       [6.],
       [9.]])>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [2],
       [2]], dtype=int32)>)

In [54]:
tf.math.top_k(tensor_two_dim, k=2)
# top values / max values first
# their indices second...
# k determines no of values...

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[3., 2.],
       [6., 5.],
       [9., 8.]])>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [2, 1],
       [2, 1]], dtype=int32)>)

In [55]:
# LINEAR ALGEBRA OPERATIONS::::
y_1 = tf.constant([[1,2],[3,4]])
y_2 = tf.constant([[1,2],[3,4]])
tf.linalg.matmul(y_1,y_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [56]:
print(y_1@y_2)
# MATRIX MULTIPLICATION SHORTCUT

tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)


In [57]:
# TRANSPOSE
print(tf.transpose(y_1))

tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [58]:
tensor_three_dim_1 = tf.constant([[ [1,2,3], [4,5,6],  [7,8,9] ],
                              [[11,12,13], [14,15,16],  [17,18,19]]])
tensor_three_dim_2 = tf.constant([[ [1,2,3], [4,5,6],  [7,8,9] ],
                              [[11,12,13], [14,15,16],  [17,18,19]]])
print(tensor_three_dim_1@tensor_three_dim_2)
# Look corresponding matrix batches to check whether multiplication is possible or not...

tf.Tensor(
[[[ 30  36  42]
  [ 66  81  96]
  [102 126 150]]

 [[510 546 582]
  [636 681 726]
  [762 816 870]]], shape=(2, 3, 3), dtype=int32)


In [59]:
tf.linalg.adjoint(tensor_two_dim)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])>

In [60]:
z_1 = tf.constant([[1,2,3],
                              [4,5,6],
                              [7,8,9]
                        ],dtype=tf.float64)
z_2 = tf.constant([[1,2,3],
                              [4,5,6],
                              [7,8,9]
                        ],dtype = tf.float64)
tf.linalg.cross(z_1,z_2)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])>

In [61]:
tf.linalg.det(z_1)

<tf.Tensor: shape=(), dtype=float64, numpy=6.66133814775094e-16>

In [62]:
tf.linalg.inv(z_1)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])>

In [63]:
# einsum same as matmul...
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.matmul(A,B))
print(np.einsum("ij,jk -> ik",A,B))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [64]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A*B)
print(np.einsum("ij,ij -> ij",A,B))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [65]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A.T)
print(np.einsum("ij -> ji",A))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [66]:
# FOR 3D MATRICES...
c = np.array([[ [1,2,3], [4,5,6],  [7,8,9] ],
                              [[11,12,13], [14,15,16],  [17,18,19]]])
d = np.array([[ [1,2,3], [4,5,6],  [7,8,9] ],
                              [[11,12,13], [14,15,16],  [17,18,19]]])
print(np.matmul(c,d))
print(np.einsum("bij,bjk -> bik",c,d))

[[[ 30  36  42]
  [ 66  81  96]
  [102 126 150]]

 [[510 546 582]
  [636 681 726]
  [762 816 870]]]
[[[ 30  36  42]
  [ 66  81  96]
  [102 126 150]]

 [[510 546 582]
  [636 681 726]
  [762 816 870]]]


In [67]:
# SUM
c = np.array([[ [1,2,3], [4,5,6],  [7,8,9] ],
                              [[11,12,13], [14,15,16],  [17,18,19]]])
print(np.sum(c))
print(np.einsum("bij-> ",c))
print(np.sum(c,axis=0))
print(np.einsum("bij-> ij ",c))

180
180
[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [68]:
A = np.random.randn(2,4,4,2) #bcij
B = np.random.randn(2,4,4,1) #bcik
np.einsum("bcij,bcik -> bcjk",A,B)

array([[[[-2.71185003],
         [ 0.75931895]],

        [[ 2.93291586],
         [ 3.35168181]],

        [[ 3.15654758],
         [-0.91745478]],

        [[-1.49560086],
         [ 0.44643616]]],


       [[[ 1.18279052],
         [-0.61333819]],

        [[ 0.82251836],
         [-3.99598359]],

        [[-0.95203228],
         [-0.0613738 ]],

        [[ 0.7318565 ],
         [-2.12507861]]]])

In [69]:
c = np.array([[ [1,2,3], [4,5,6],  [7,8,9] ],
                              [[11,12,13], [14,15,16],  [17,18,19]]])
print(c.shape)
c_expanded = tf.expand_dims(c,axis=0)
print(c_expanded)
# axis => 0 -> add at first  1-> at 2nd  2 -> at 3rd

(2, 3, 3)
tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[11 12 13]
   [14 15 16]
   [17 18 19]]]], shape=(1, 2, 3, 3), dtype=int64)


In [70]:
c_squeezed = tf.squeeze(c_expanded, axis=0)
print(c_squeezed)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]], shape=(2, 3, 3), dtype=int64)


In [71]:
a = tf.constant([[1,2,3],[4,5,6]])
tf.reshape(a,[6,])

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [72]:
tf.reshape(a,[3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [73]:
a = tf.constant([[1,2,3,],[4,5,6]])
b = tf.constant([[1,2,3],[4,5,6]])
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [74]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]], dtype=int32)>

In [75]:
# tf.stack() creates a new axis and adds up...
tf.stack([a,b],axis=0)
# 2,3 2,3   2,2,3  axis = 0   added at 0 index

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [76]:
tf.stack([a,b],axis=1)
# added at index1

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]]], dtype=int32)>

In [78]:
a = tf.constant([[1,2,3],[4,5,6]])
padding = tf.constant([[1,1],[2,2]])
print(tf.pad(a,padding,"CONSTANT"))
print(tf.pad(a,padding,"REFLECT"))
print(tf.pad(a,padding,"SYMMETRIC"))

tf.Tensor(
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[2 1 1 2 3 3 2]
 [2 1 1 2 3 3 2]
 [5 4 4 5 6 6 5]
 [5 4 4 5 6 6 5]], shape=(4, 7), dtype=int32)


In [83]:
# tf.gather() => helps in indexing
# no negative indexing
a = tf.constant([1,2,3,4,5,6])
print(a[3].numpy())
print(tf.gather(a,3).numpy())
print(tf.gather(a,[3,5]).numpy())
# axis = 0/1 also there in case more Dim..

4
4
[4 6]


In [85]:
# RAGGED TENSORS
z = tf.constant([[1,2,3],
                   [4,5,6],
                   [7,8,9]],dtype=tf.float64)
print(z.shape)
# Tensors should be rectangular else error
# Tensorflow deals with that using dagged tensors...
z1 = tf.ragged.constant([[1,2,3],
                   [4,],
                   [7,8,9,10,3]],dtype=tf.float64)
print(z1.shape)
# No exact cols so none...

(3, 3)
(3, None)


In [86]:
# SPARSE TENSORS => Data with many 0s
t = tf.sparse.SparseTensor(
    indices = [[1,1],[3,4]], values = [11,56], dense_shape = [5,6]
)
print(tf.sparse.to_dense(t))

tf.Tensor(
[[ 0  0  0  0  0  0]
 [ 0 11  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0 56  0]
 [ 0  0  0  0  0  0]], shape=(5, 6), dtype=int32)


In [87]:
# STRING TENSORS
t = tf.constant(["kyu","hua","aisa"])
print(t)

tf.Tensor([b'kyu' b'hua' b'aisa'], shape=(3,), dtype=string)


In [88]:
tf.strings.join(t)

<tf.Tensor: shape=(), dtype=string, numpy=b'kyuhuaaisa'>

In [90]:
# VARIABLES
x = tf.constant([1,2,3])
x_var = tf.Variable(x,'Var1')
print(x_var)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [91]:
v = tf.Variable(1)
v.assign(2)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>


In [93]:
v.assign_add(5)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>


In [97]:
with tf.device('GPU:0'):
  x = tf.Variable(0.2)
print(x.device)

/job:localhost/replica:0/task:0/device:CPU:0
